In [1]:
import numpy as np

In [10]:
#### Making Activation Function (sigmoid)
def activation(x):
    return 1/(1+np.exp(-x))

In [7]:
activation(2)

0.8807970779778823

In [8]:
activation(1)

0.7310585786300049

In [9]:
activation(0)

0.5

In [11]:
# Creating input samples
training_inputs = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
training_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [12]:
## Creating output samples
training_outputs = np.array([[0],[1],[1],[0]])
training_outputs

array([[0],
       [1],
       [1],
       [0]])

In [23]:
### weights
np.random.seed(20) # To fix the sample 
weights = np.random.random((3,1))
weights

array([[0.5881308 ],
       [0.89771373],
       [0.89153073]])

In [24]:
input_layer = training_inputs
mul = np.dot(input_layer,weights)
mul 

array([[0.89153073],
       [2.37737526],
       [1.47966153],
       [1.78924446]])

In [25]:
outputs = activation(mul)
outputs

array([[0.70920596],
       [0.9150857 ],
       [0.81452145],
       [0.85683462]])

In [26]:
outputs.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

In [27]:
input_layer.shape

(4, 3)

In [28]:
weights.shape

(3, 1)

In [29]:
outputs = activation(mul)
outputs

array([[0.70920596],
       [0.9150857 ],
       [0.81452145],
       [0.85683462]])

In [30]:
def gradient(x):
    return x*(1-x)

In [34]:
for i in range(500):
    input_layer = training_inputs
    mul = np.dot(input_layer,weights)
    outputs = activation(mul)
    error = training_outputs - outputs
    adjustments = error *gradient(outputs)
    weights += np.dot(input_layer.T,adjustments)
    if i%20==0:
        print(error)

[[-0.04619472]
 [ 0.03749091]
 [ 0.03016401]
 [-0.03723263]]
[[-0.04522421]
 [ 0.03670719]
 [ 0.02953897]
 [-0.03645573]]
[[-0.04431077]
 [ 0.03596942]
 [ 0.02895052]
 [-0.0357245 ]]
[[-0.04344908]
 [ 0.03527335]
 [ 0.02839525]
 [-0.03503466]]
[[-0.04263448]
 [ 0.03461521]
 [ 0.02787017]
 [-0.03438248]]
[[-0.04186287]
 [ 0.03399171]
 [ 0.02737267]
 [-0.03376469]]
[[-0.04113064]
 [ 0.03339995]
 [ 0.02690043]
 [-0.03317839]]
[[-0.04043459]
 [ 0.03283736]
 [ 0.0264514 ]
 [-0.03262102]]
[[-0.03977186]
 [ 0.03230162]
 [ 0.02602375]
 [-0.03209028]]
[[-0.0391399 ]
 [ 0.0317907 ]
 [ 0.02561584]
 [-0.03158415]]
[[-0.03853643]
 [ 0.03130274]
 [ 0.02522622]
 [-0.03110078]]
[[-0.03795938]
 [ 0.0308361 ]
 [ 0.02485356]
 [-0.03063854]]
[[-0.03740691]
 [ 0.03038928]
 [ 0.02449669]
 [-0.03019595]]
[[-0.03687733]
 [ 0.02996093]
 [ 0.02415451]
 [-0.02977165]]
[[-0.03636911]
 [ 0.02954982]
 [ 0.02382605]
 [-0.02936443]]
[[-0.03588088]
 [ 0.02915483]
 [ 0.02351044]
 [-0.02897319]]
[[-0.03541137]
 [ 0.0287

In [35]:
weights

array([[ 7.26018188],
       [-0.21923359],
       [-3.41385698]])

In [36]:
outputs.round()

array([[0.],
       [1.],
       [1.],
       [0.]])